# Generated by Django 4.2.4 on 2023-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_brand_remove_product_country_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_busket',
            field=models.BooleanField(default=False),
        ),
    ]
