# Generated by Django 4.2.4 on 2023-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Неизвестно', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.TextField(default='Неизвестно'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='Неизвестно', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
